--mi primer bloque pl-sql
--no vamos a declarar ninguna variable, empezamos con el BEGIN


--MODO DE DEPURACION
SET SERVEROUTPUT ON; 

BEGIN
--AQUI VA LA LOGICAA
DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
--DBMS: DATABASE MANAGEMENT SYSTEM
-- OUTPUT : SALIDA
--PUT_LIE: FUNCION PARA IMPRIMIR UN A LINEA
END;
/

--SEGUNDO BLOQUE PL SQL USANDO DECLARACION DE VARIABLES
DECLARE
EDAD INTEGER;
NOMBRE VARCHAR2 (40);
DIAS INTEGER;
BEGIN
--ASIGNANDO ESAS VARIABLES
--USAMOS := PARA ASIGNAR VALORES
EDAD:=20;
--SACANDO LA EDAD EN DIAS
DIAS:=EDAD*365;
NOMBRE:= 'JIMENA';
--USAMOS || PARA CONCATENAR
DBMS_OUTPUT.PUT_LINE('BUENOS DIAS '|| NOMBRE || ' TU EDAD EN DIAS ES ' || DIAS);
END;
/

--EJERCICIO 3, LAS TABLS
 CREATE TABLE CHICOS 
 (  
    ID INTEGER PRIMARY KEY,
    VALOR INTEGER
  );
  
  CREATE TABLE GRANDES 
  (
    ID INTEGER PRIMARY KEY,
    VALOR INTEGER
  );
  
  --GEERAR BLOQE PL-SQL QUE TENGA DECLARADA UNA VARIABLE DE DE TIPO INTEGER QUE SE LLAME EDAD Y QUE AL ASIGNAR UN VALOR MAYORI A 18, INSERTE LA EDAAD EN UN CNPO 
  --DE LA  TABLA GRANDES Y SI ES MENOR O IGUAL A 18,QUE HAGA LA INSERCIN EN LA TABLA CHICMJOS
  
  --USANDO ESTRUCTURAS DE CONTROL
  
DECLARE
EDAD INTEGER;
BEGIN
EDAD:=40;
IF EDAD >18 THEN
INSERT INTO GRANDES VALUES(1,EDAD);
--EL ID ES 1, LA VARIABLE DE SUSTITUCION ES LA EDAD, ARRIBA ESTA ASIGNADA, VALE 40
ELSE
INSERT INTO CHICOS VALUES(1,EDAD);
ENd IF;
END;
/

--LO PROBLAMOS
SELECT * FROM GRANDES;