--Crear la tabla sitio_adultos
CREATE TABLE SITIO_ADULTOS
(
  ID_ADULTO INTEGER,
  NOMBRE VARCHAR2(60),
  EDAD INTEGER,
  CONSTRAINT PK_EL_ID PRIMARY KEY (ID_ADULTO)
  );
  
  --GENERAR UN DISPARADOR QUE IMPIDA CREAR UN REGISTRO SI LA EDAD
  --INGRESADA ES MENOR DE 18. :))
  CREATE OR REPLACE TRIGGER DISP_ADULTOS BEFORE INSERT ON SITIO_ADULTOS
  --CUERPO DEL DISPARADOR
  --PARA QUE NO MARQUE ERROR:
  FOR EACH ROW --OBVI POR CADA RENGLON PARA UNA INSERCION MASIVA :P
  BEGIN
  --LA LOGICA:
  IF :NEW.EDAD <18 THEN --: NEW PALABRA RESERAVADA, INVOCA UN CAMPO DE LA TABLA 
  RAISE_APPLICATION_ERROR (-200001, 'ESTAS CHAVO'); -- -200001 ES UN CODIGO DE ERROR, ES UN COMODIN....
  END IF;
  END;
  /
  --TODOS LOS ERRORES TIENEN CLVADE DE ERROR (ID DE ERROR)
  --  RAISE_APPLICATION_ERROR FUNCION ES EXCEPCION
  --SI SE CUMPLE LA CONDICION, SE LANZA LA EXEPCION
  
  
  --PARA COMPROBAR:
  SELECT * FROM SITIO_ADULTOS
  
  
  /*
   E L E R R O R : )
  INSERT INTO SITIO_ADULTOS VALUES(2,'UGHUGU',14);
  Error que empieza en la línea 31 del comando:
INSERT INTO SITIO_ADULTOS VALUES(2,'UGHUGU',14)
Informe de error:
Error SQL: ORA-21000: el argumento de número de error para raise_application_error de -200001 está fuera de rango
ORA-06512: en "SYSTEM.DISP_ADULTOS", línea 4
ORA-04088: error durante la ejecución del disparador 'SYSTEM.DISP_ADULTOS'
21000. 00000 -  "error number argument to raise_application_error of %s%s is out of range"
*Cause:    
*Action:   Use an error number in the range of -20000 to -20999, inclusive.*/

