--Crear la tabla s
CREATE TABLE GENERALL
(
  ID_GRAL INTEGER,
  NOMBRE VARCHAR2(60),
  EDAD INTEGER,
  CONSTRAINT PK_EL_IDGRAL PRIMARY KEY (ID_GRAL)
  );
  
  
CREATE TABLE ESPEJO_MAYORES
(
  ID_MAYORES INTEGER,
  NOMBRE VARCHAR2(60),
  EDAD INTEGER,
  CONSTRAINT PK_EL_IDMAYOR PRIMARY KEY (ID_MAYORES)
  );
  
  
CREATE TABLE ESPEJO_MENORES
(
  ID_MENOR INTEGER,
  NOMBRE VARCHAR2(60),
  EDAD INTEGER,
  CONSTRAINT PK_EL_IDMENOR PRIMARY KEY (ID_MENOR)
  );
  
  CREATE OR REPLACE TRIGGER DISP_MAESTRA AFTER INSERT ON GENERALL
  FOR EACH ROW
  BEGIN
  IF :NEW.EDAD>18 THEN
  INSERT INTO ESPEJO_MAYORES VALUES (:NEW.ID_MAYOR, :NEW.NOMBRE, :NEW.EDAD);
  --SE INSERTAN LOS NUEVOS CAMPOS, COMO EN LA MAESTRA
  ELSE
  INSERT INTO ESPEJO_MENORES VALUES (:NEW.ID_MENOR, :NEW.NOMBRE, :NEW.EDAD);
  --SE INSERTAN LOS NUEVOS CAMPOS, COMO EN LA MAESTRA :P
  END IF;
  END;
  /
  --LA GENERAL VA A ESTAR VACIA :99
  