-- CREAMOS LA TABLA ALMACEN
CREATE TABLE ALMACEN
(
  NUMERO_ALMACEN INTEGER,
  UBICACION_ALMACEN VARCHAR2(50),
  CONSTRAINT PK_NUM_ALMACEN PRIMARY KEY(NUMERO_ALMACEN)
);

--PRIMERO SE DEFINE EL NOMBRE Y TIPO DE CAMPO
--LUEGO ALS RESTRICCIONES (CONSTRAINT) EL NOMBRE DEL CONSTRAINT, ENTRE () EL CAMPO DEL COSNT.

--CREAMOS LA TABLA CLIENTE QUE SE RELACIONA A ALMACEN
CREATE TABLE CLIENTE
(
  NUMERO_CLIENTE INTEGER,
  NUMERO_ALMACEN INTEGER, --ESTE SER AEL FK
  NOMBRE_CLIENTE VARCHAR2(50),
  CONSTRAINT PK_NUM_CLIENTE PRIMARY KEY (NUMERO_CLIENTE),
  CONSTRAINT FK1_NUM_ALMACEN FOREIGN KEY (NUMERO_ALMACEN) REFERENCES ALMACEN(NUMERO_ALMACEN)
);

--PROCEDIMIENTO GUARDAR ALMACEN
CREATE OR REPLACE PROCEDURE GUARDAR_ALMACEN(MI_ID IN INTEGER, MI_UBI IN VARCHAR2)
AS
BEGIN
INSERT INTO ALMACEN VALUES(MI_ID,MI_UBI);
END;
/

--PROCEDIMIENTO GUARDAR CLIENTE
CREATE OR REPLACE PROCEDURE GUARDAR_CLIENTE(MI_ID IN INTEGER, ID_ALMACEN IN INTEGER, NOMB_CLIENTE IN VARCHAR2)
AS
BEGIN
INSERT INTO CLIENTE VALUES(MI_ID, ID_ALMACEN, NOMB_CLIENTE);
END;
/

--GENERAR LA TABLA VENDEDOR
CREATE TABLE VENDEDOR
(
  NUMERO_VENDEDOR INTEGER,
  NOMBRE_VENDEDOR VARCHAR2(50),
  AREA_VENTAS VARCHAR2(50),
  CONSTRAINT PK_NUM_VEND PRIMARY KEY (NUMERO_VENDEDOR)
);

--GENERAR LA TABLA VENTAS
CREATE TABLE VENTAS
(
  ID_VENTAS INTEGER,
  NUMERO_CLIENTE INTEGER,
  NUMERO_VENDEDOR INTEGER,
  MONTO_VENTAS FLOAT,
  CONSTRAINT PK_ID_VENTAS PRIMARY KEY (ID_VENTAS),
  CONSTRAINT FK1_NUM_VENDEDOR FOREIGN KEY (NUMERO_VENDEDOR) REFERENCES VENDEDOR (NUMERO_VENDEDOR),
  CONSTRAINT FK2_NUM_CLIENTE FOREIGN KEY (NUMERO_CLIENTE) REFERENCES CLIENTE (NUMERO_CLIENTE)
);

CREATE OR REPLACE PROCEDURE GUARDAR_VENDEDOR (ID_VENDEDOR IN INTEGER,NOMB_VEND IN VARCHAR2, MI_AREA IN VARCHAR2)
AS
BEGIN
INSERT INTO VENDEDOR VALUES(ID_VENDEDOR,NOMB_VEND,MI_AREA);
END;
/

--COMO EL ID DE VENTAS ES AUTOINCREMENTABLE, HACEMOS UN CURSOR.

--YA QUE ESTA LA TABLA, HACEMOS LA SECUENCIA QUE CONTORLA LA PK.

CREATE SEQUENCE SEC_VENTAS
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

--AHORA EL PROCEDIMIENTO PARA ASOCIAL LA SECUENCIA A LA TABLA DE VENTAS

CREATE OR REPLACE PROCEDURE GUARDAR_VENTAS(ID_VENTAS OUT INTEGER, NUM_CLIENTE IN INTEGER,
NUM_VENDEDOR IN INTEGER, MI_MONTO IN FLOAT)
AS
BEGIN
SELECT SEC_VENTAS.NEXTVAL INTO ID_VENTAS FROM DUAL;
INSERT INTO VENTAS VALUES(ID_VENTAS, NUM_CLIENTE, NUM_VENDEDOR, MI_MONTO);
END;
/
