 -- ESTE PROCEDIMIENTO VA A EXISTR EN LA BASE DE DATOS 4 EVERRRR HASTA QUE LOE LIMINEMOSN XD
 
 --POR EJEMPLO, CUANDO QUERAMOS IMPRIIR ALGO, EN LUGAR DE CHUTARNOS TODA LA LINEA DE DBMS...
 --YA SOLO TENEMOS QUE ESCRIBIR "IMPRIMIR" : TA-RAAAN!!!
--PARA MODIFICAR Y COMPILAR CADA E QUE QUERAMOS
--USAMOS CREATE POR SER UN OBJETO DE LA BASE DE DATOS
--USAMOS LA PALABRA RESERVADA PROCEDURE, POR SER UN PROCEDIMIENTO ALMACENADO
--SEGUIDO DEL NOMBRE Y LOS ARGUMENTOS. LOS ARGUMENTOS SON ENTRE PARENTESIS
-- ARGUMENTO: (NOMBRE, IN/OUT, TIPO DE DATO)

--ESTA LINEA ES PARA ACTIVAR LA SALIDA DE LA CONSOLITA :9 
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE IMPRIMIR (MENSA IN VARCHAR2)
--DECLARACION DE VARIABLES LOCALES (PUEDE SER EN EL MISMO RENGLON)
AS 
BEGIN
--VA A IMPRIMIR LO QUE NOSOTROS LE PASAMOS COMO ARGUMENTO
DBMS_OUTPUT.PUT_LINE (MENSA);
END;
/

--VAMOS A INVOCARLO INTERNAMENTE, ES DECIR DESDE AQUI EN ORACLE XD
--SE INVOCA DENTRO DE 2 BLOQUES PL-SQL
BEGIN
IMPRIMIR('VAMOS A VER SI FUNCIONA');
END;
/
--SE SUPONE QUE TIENE QUE IMPRIMIR ESTO DE ARRIBA EN PANTALLA...

--EJERCICIO #2. 
--A)
CREATE TABLE DANCE
( ID INTEGER PRIMARY KEY, 
  MENSAJE VARCHAR2 (80));

--B)
CREATE OR REPLACE PROCEDURE GUARDAR_DANCE(VAR1 IN INTEGER, VAL2 IN VARCHAR2)
AS
  BEGIN
  --ESCRIBIMOS EN EL INSERT LAS VARIABLES DE SUSTITUCION, EN LUGAR DE LAS DE LA TABLA:
    INSERT INTO DANCE VALUES(VAL1,VAL2);
  END:
  /
  --PROBAMOS INTERNAMENTE 
  BEGIN
  GUARDAR_DANCE(1,'MI PRIMER MENSAJITO');
  END;
  /
  select * from dance; 


